blank_issues_enabled: true
contact_links:
  - name: Ask, answer, share
    url: https://github.com/qgis-deployment/qgis-deployment-toolbelt-cli/discussions/
    about: Have a question or need help? Have an answer or idea to share? Connect with the community on our discussion board
  - name: Implementing QDT in your organization
    url: https://qgis-deployment.github.io/qgis-deployment-toolbelt-cli/misc/funding.html
    about: Want to contract to deploy QDT in your organization or to fund or sponsor a feature or a bug fix?
