name: "🎳 Tester"

on:
  push:
    branches: [main]
    paths:
      - "**/*.py"
      - ".github/workflows/tests.yml"

  pull_request:
    branches: [main]
    paths:
      - "**/*.py"
      - ".github/workflows/tests.yml"
      - "requirements/*.txt"

env:
  PROJECT_FOLDER: "qgis_deployment_toolbelt"
  PYTHON_VERSION: 3.8

jobs:
  unit-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Get source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
          cache-dependency-path: "requirements/*.txt"

      - name: Install project requirements
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U -r requirements.txt
          python -m pip install -U -r requirements/testing.txt

      - name: Install project as a package
        run: python -m pip install -e .

      - name: Unit tests
        run: pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
