name: "🎳 Tester"

on:
  push:
    branches: [main]
    paths:
      - "**/*.py"
      - ".github/workflows/tests.yml"

  pull_request:
    branches: [main]
    paths:
      - "**/*.py"
      - ".github/workflows/tests.yml"
      - "requirements/base.txt"
      - "requirements/testing.txt"
      - tests/fixtures/

env:
  PROJECT_FOLDER: "qgis_deployment_toolbelt"

jobs:
  unit-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-22.04, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "requirements/*.txt"

      - name: Install project requirements
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U -r requirements.txt
          python -m pip install -U -r requirements/testing.txt

      - name: Install project as a package
        run: python -m pip install -e .

      - name: Unit tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QDT_LOGS_LEVEL: 4
        run: pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          env_vars: OS,PYTHON
          flags: unittests
          name: Code Coverage for unittests on [${{ matrix.os }}.python-${{ matrix.python-version }}]
        env:
          OS: ${{ matrix.os }}
          PYTHON: ${{ matrix.python-version }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  integration-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-22.04, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "requirements/*.txt"

      - name: Install project requirements
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U -r requirements.txt

      - name: Install project as a package
        run: python -m pip install -e .

      - name: QDT - Echoing help
        run: qdt --help

      - name: QDT - Echoing version
        run: qdeploy-toolbelt --version

      - name: QDT - Sample scenario
        run: qgis-deployment-toolbelt --verbose

      - name: QDT - Sample scenario
        run: qgis-deployment-toolbelt --verbose --no-logfile
